name: Generate Synthetic Dataset
on:
  workflow_dispatch:
    inputs:
      FONT_WHITELIST:
        description: "Comma-separated fonts"
        default: "Noto Sans,DejaVu Sans,Roboto,Open Sans,Arial,Times New Roman,Courier New"
        required: false
      PTSIZE_MIN:
        description: "Min pt size"
        default: "12"
        required: false
      PTSIZE_MAX:
        description: "Max pt size"
        default: "22"
        required: false
      RESOLUTION:
        description: "DPI"
        default: "300"
        required: false
jobs:
  synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Tesseract
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-eng fonts-dejavu fonts-noto
      - name: Generate synthetic TIFF+BOX
        env:
          FONT_WHITELIST: ${{ github.event.inputs.FONT_WHITELIST }}
          PTSIZE_MIN: ${{ github.event.inputs.PTSIZE_MIN }}
          PTSIZE_MAX: ${{ github.event.inputs.PTSIZE_MAX }}
          RESOLUTION: ${{ github.event.inputs.RESOLUTION }}
        run: |
          chmod +x scripts/gen_synthetic_dataset.sh || true
          ./scripts/gen_synthetic_dataset.sh
      - name: Upload synth artifact
        uses: actions/upload-artifact@v4
        with:
          name: synth-dataset
          path: dataset/synth/train
          if-no-files-found: warn
