name: Train Oriogo (self-hosted)
on:
  workflow_dispatch:
    inputs:
      MAX_ITERATIONS:
        description: "Max iterations for finetune"
        default: "20000"
        required: false
      PSM:
        description: "PSM"
        default: "6"
        required: false
      FONT_WHITELIST:
        description: "Comma-separated font whitelist"
        default: "Noto Sans,DejaVu Sans,Roboto,Open Sans,Arial,Times New Roman,Courier New"
        required: false
permissions:
  contents: write
  actions: read
jobs:
  train:
    # add your runner label if you use one, e.g. [self-hosted, macos]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Show env
        run: |
          uname -a || true
          tesseract --version || true
          which text2image || true
          which lstmtraining || true
      - name: Train (finetune from ces)
        env:
          MAX_ITERATIONS: ${{ github.event.inputs.MAX_ITERATIONS }}
          PSM: ${{ github.event.inputs.PSM }}
          FONT_WHITELIST: ${{ github.event.inputs.FONT_WHITELIST }}
        run: |
          chmod +x scripts/train_oriogo_tesstrain_plus.sh || true
          ./scripts/train_oriogo_tesstrain_plus.sh
      - name: Verify charset
        run: |
          chmod +x scripts/verify_charset.sh || true
          if [ -f ./oriogo.traineddata ]; then
            ./scripts/verify_charset.sh oriogo ./data/required_chars.txt || true
          else
            echo "No oriogo.traineddata produced."; exit 1
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: oriogo-traineddata
          path: |
            oriogo.traineddata
            oriogo.*
          if-no-files-found: error
