name: Release Oriogo
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g., v0.1.0)"
        required: true
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Oriogo ${{ github.event.inputs.tag }}
          files: |
            oriogo.traineddata
            oriogo.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
