name: Setup and Check Tesseract
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libtesseract-dev libleptonica-dev
          tesseract --version

      - name: Verify setup
        run: |
          echo "Tesseract has been installed successfully."
